### PR TITLE
Refactor/optional umi index

### PR DESCRIPTION
**Pull request by mihirsamdarshi**

### CODE REVIEW

**Comment by archanaraja** [comment]
Except for a the below few minor issues the script works very well and produces the expected outputs.
- Modify the make_json_rnaseq.py to make the blocks that generates I1 files optional.
@mihirsamdarshi

**Comment by archanaraja** [comment]
The script works as expected and produces the right outputs.  @mihirsamdarshi : Can you please modify the make_json_rnaseq.py to make the blocks that generates I1 files optional and use the make_json_rnaseq.py from the master but for the two minor changes the pipeline is working. Thank you.

**Comment by mihirsamdarshi** [comment]
@archanaraja I have updated the script to make the index files optional

**Comment by archanaraja** [comment]
Tested the code. Added option to support multiple versions of rat and human genome versions

**Review by archanaraja — APPROVED** [review]
Tested the code and works as expected.

**Pull request merged**
